# Log agent (fluentd-cloudwatch) configuration
logAgent:
  configFiles: "files/prod/*.conf"
  image:
    repository: "fluent/fluentd-kubernetes-daemonset"
    tag: "v1.7.3-debian-cloudwatch-1.0"

# Metric agent (cloudwatch-agent) configuration

metricAgent:
  configFiles: "files/prod/cloudwatch-agent.json"